version: '3'

services:
  backend:
    image: ghcr.io/obiwan87/cleanup-sicily-reporter:latest
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - FIREBASE_CREDENTIALS=/app/firebase-admin.json
    volumes:
      - ${FIREBASE_CREDENTIALS_PATH}:/app/firebase-admin.json