name: Build and Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u obiwan87 --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:latest ./backend

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:latest

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/deploy
            
            echo "Pull latest image..."
            docker compose pull
            
            echo "Restart container with env vars..."
            SPRING_PROFILES_ACTIVE=prod \
            FIREBASE_CREDENTIALS=/app/firebase-admin.json \
            FIREBASE_ADMIN_PATH=/home/deploy/firebase-admin.json \
            docker compose up -d
            
            echo "Cleanup old images..."
            docker image prune -f